name = "ghwsee-indexable-redirect"
account_id = "c455dc5b9661861484370320794ab63c"
workers_dev = true
compatibility_date = "2022-02-27"
main = "dist/worker.js"

[build]
command = "npm install && npm run build"
