[package]
name = "github-wiki-see"
version = "0.1.0"
authors = ["Nelson Chen <crazysim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
env_logger = "0.8.3"
nipper = "0.1.9"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }

actix-rt = "2.2.0"
askama = "0.10.5"
askama_actix = "0.11.1"
tokio = { version = "1.6.1", features = ["full"] }
regex = "1.5.4"
