[package]
name = "actix-web-play"
version = "0.1.0"
authors = ["Nelson Chen <crazysim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
env_logger = "0.8.3"
nipper = "0.1.9"
reqwest = "0.11.2"
actix-rt = "2.1.0"
